USE ROLE ACCOUNTADMIN; 

CREATE STORAGE INTEGRATION IF NOT EXISTS GCS_EDINET_INT 
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'GCS'
    ENABLED = TRUE 
    STORAGE_ALLOWED_LOCATIONS = (
        'gcs://edinet-growth-pipeline-data-shawn-20260606/'
    );