USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION GCS_EDINET_NOTIFICATION_INT
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = TRUE
  GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/edinet-growth-pipeline/subscriptions/edinet-gcs-snowpipe-sub';

DESC NOTIFICATION INTEGRATION GCS_EDINET_NOTIFICATION_INT;