USE ROLE ACCOUNTADMIN;
USE DATABASE EDINET_DB;
USE SCHEMA RAW;

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('DOCUMENT_METADATA_PIPE');

SELECT SYSTEM$PIPE_STATUS('EDINET_COMPANY_MASTER_PIPE');

SELECT SYSTEM$PIPE_STATUS('RAW_ANNUAL_REPORT_VALUES_PIPE');

SELECT COUNT(*) AS document_metadata_count
FROM DOCUMENT_METADATA_RAW;

SELECT COUNT(*) AS company_master_count
FROM EDINET_COMPANY_MASTER_RAW;

SELECT COUNT(*) AS annual_report_values_count
FROM RAW_ANNUAL_REPORT_VALUES;

SELECT *
FROM DOCUMENT_METADATA_RAW
ORDER BY loaded_at DESC
LIMIT 10;

SELECT *
FROM RAW_ANNUAL_REPORT_VALUES
ORDER BY loaded_at DESC
LIMIT 10;