name: CI Pipeline 

on:
  push:
    branches:
      - main 
      - "feature/**"
    paths: 
     - "pipeline/**"
     - "pyproject.toml"
     - "uv.lock"
     - "Dockerfile"
     - ".dockerignore"
     - ".github/workflows/ci-pipeline.yml"

     
  pull_request:
    branches:
        - main 
    paths: 
        - "pipeline/**"
        - "pyproject.toml"
        - "uv.lock"
        - "Dockerfile"
        - ".dockerignore"
        - ".github/workflows/ci-pipeline.yml"

jobs: 
  pipeline-check: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install uv 
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Python 
        run: uv python install 

      - name: Install dependencies 
        run: uv sync --frozen 

      - name: Check Python syntax 
        run: uv run python -m compileall pipeline

      - name: Check pipeline import 
        run: uv run python -c "import pipeline.main; print('Pipeline import OK')"

      - name: Run tests 
        run: uv run pytest tests/pipeline/





